### ISSUE TITLE
WinSteno

### ISSUE THREAD

**Issue by ahmedkandel** [Skaaal/StenturaArduino#1]
Hello,
I have a question not related to Arduino but to Stentura.

I am building a desktop app that connects to "Stentura 200 SRT" and "Michela" hardware then it elaborates the data flow coming over the serial port and transmit it to MS Word.

I have done the part related to "Michela" as it contains EPROM and it transmits ASCII directly, while for "Stentura" with Italian board by "Stenotype Italia Srl" I get binary data as you described "Every key has a unique value, chords are just the individual values OR'd together."

I didn't find any docs related to that matter, Can you give me some indications on how to elaborate those bytes to get the cord or keys?

Thanks

**Comment by PBrunot** [comment]
Hi Ahmed,

You can find the magic values bykeys in the Arduino source code:
https://github.com/PBrunot/StenturaArduino/blob/master/Software/winsteno2000/winsteno2000.ino

Your desktop app is interesting. I'd like to know more about it, are you publishing it on GitHub?

**Comment by ahmedkandel** [comment]
Hi Pascal,

Thanks for the swift reply. Yes, I found the single keys values in your code and it was so helpful to me to understand how the machine works.

What I am missing is how to elaborate combinations of keys "cords". So if you have any docs, code or libraries for WinSteno2000 protocol that you can share it will be much helpful.

The App we are building is a project for one of our clients that needs to connect "Michela & Melani" machines to PC and use it as a keyboard so the stenotypist "who prefers using those machines over normal keyboard" can type faster on PC.

The Michela machine sends ASCII over the serial port so I can search on the user dictionary and output the correct word. While for the Melani machine I am searching how to convert the binary coming over the serial port to the equivalent cord to check it against the dictionary.

Thanks again for your help.
